### ISSUE TITLE
module.getExports is not a function

### ISSUE THREAD

**Issue by micaelmbagira** [jspm/jspm-cli#1760]
I have a Angular 1 app with Typescript using `jspm@0.17.0-beta.13`. When I run `builder.buildStatic`, I have this error:
> TypeError: module.getExports is not a function
    at webapp/node_modules/rollup/dist/rollup.js:6451:11

````
const Builder = require('jspm').Builder;
const builder = new Builder('./', 'jspm.config.js');
builder.buildStatic(
    `${conf.path.src('index.js')} + ${conf.path.tmp('templateCacheHtml.js')}`,
    conf.path.tmp('index.js')
  ).then(() => done(), done);
````
However if I pass `{rollup: false}` to the `buildStatic` function, it works. Plus, it doesn't happen if I use ES6 or ES5, only with Typescript.

**Comment by guybedford** [comment]
This could well be a special edge case bug for the partial Rollup optimization process. If you can share an example that includes the dependency tree information that would help a lot to look into it further.

**Comment by micaelmbagira** [comment]
Yes, here is one https://github.com/FountainJS/jspm-replication-1760

**Comment by guybedford** [comment]
Thanks, this seems like a Rollup bug to me, so it's blocked on https://github.com/systemjs/builder/issues/570.

**Comment by guybedford** [comment]
Rollup has been updated so this should work with 0.17.0-beta.18.

**Comment by micaelmbagira** [comment]
The problem is still happening unfortunately, even after updating. Do you want a replication project ?

**Comment by micaelmbagira** [comment]
Actually it's not completely solved: https://github.com/jspm/jspm-cli/issues/1909

**Comment by guybedford** [comment]
I take it #1909 is a different issue to this `getExports` one though? But it sounds like your Angular2 build is working ok, so is it the Angular 1 error you're still worried about?

**Comment by micaelmbagira** [comment]
Sorry for the delay, Angular 1 error concerning this issue is solved.
