### ISSUE TITLE
error TS1192: Module '"jquery"' has no default export.

### ISSUE THREAD

**Issue by delebash** [jspm/jspm-cli#1497]
Windows 7 x64
jspm 0.16.15
gulp-typescript 2.9.2
typescript 1.7.3

I have read a few issues regarding this and I think its is a System.js problem but I am not sure.

I  am trying to import jquery inside of an Aurelia project using
import $ from 'jquery';

I added jquery to typing via tsd install jquery
after running gulp-typescript I get the above error.

Here are a few articles I have read about the problem
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/6315
https://github.com/Microsoft/TypeScript/issues/5285

I have tried the  flag   "allowSyntheticDefaultImports" : true and false with the same result

If I import jquery using import * as $ from 'jquery'; everything works fine no errors

**Comment by guybedford** [comment]
The `allowSyntheticDefaultImports` option does sound like the right fix, but note that that only works on the latest TypeScript 1.8.0 beta. Are you definitely running that beta version here?

**Comment by delebash** [comment]
no, I will update and give it a try


Date: Wed, 3 Feb 2016 11:07:57 -0800

**Comment by delebash** [comment]
Thanks, that fixed it.
