### ISSUE TITLE
Long.js NPM package works bundled in jspm 0.6.11 but not jspm 0.6.12

### ISSUE THREAD

**Issue by blixt** [jspm/jspm-cli#1194]
This is a tricky one. When bundled with `jspm bundle-sfx`, my app is failing on a line that uses `Long.fromNumber(…)` from the [Long.js library][long], with the error "Long.fromNumber is not a function" and `Long` is just an empty `Object` instance instead of the module (its `constructor` is `Object` and it's using the `Object.prototype` prototype, but it has no own properties).

I've narrowed the issue down to working with jspm 0.6.11 (clean install) but not with 0.6.12 (clean install). Simply creating a single JavaScript file with `import Long from 'long'; console.log(Long.fromNumber(123));` works, however, so the issue must stem from a combination of reasons.

Looking at [the source code of Long.js][long-source], it tries to support all types of modules at once, which is possibly part of the problem. Did something change between jspm 0.6.11 and 0.6.12 that could cause this to happen? I'll try to debug more and report here.

[long]: https://github.com/dcodeIO/Long.js
[long-source]: https://github.com/dcodeIO/Long.js/blob/master/dist/Long.js

**Comment by guybedford** [comment]
There was a bug introduced in https://github.com/jspm/jspm-cli/issues/1195. Perhaps this is related?

**Comment by blixt** [comment]
@guybedford In my sfx bundle I can't find any mention of `typeof req` (or `typeof require`), nor are the `require(…)` calls wrapped in conditionals, so it doesn't seem to be the same issue, no. What's the easiest way to build the project with SystemJS builder master?

**Comment by blixt** [comment]
Yep, to confirm changing from this:

```javascript
$__System.registerDynamic("11d", ["7"], true, function(req, exports, module) {
  ;
  var global = this,
      __define = global.define;
  global.define = undefined;
  "format cjs";
  (function(process) {
// ... the module code ... //
  })(req('7'));
  global.define = __define;
  return module.exports;
});
```

to this:

```javascript
$__System.registerDynamic("11d", ["7"], true, function(require, exports, module) {
  ;
  var global = this,
      __define = global.define;
  global.define = undefined;
  "format cjs";
  (function(process) {
// ... the module code ... //
  })(require('7'));
  global.define = __define;
  return module.exports;
});
```

fixes the issue!

**Comment by guybedford** [comment]
Great, thanks closing as a duplicate of https://github.com/jspm/jspm-cli/issues/1195.
