### ISSUE TITLE
Jspm update:  toMap.startsWith is not a function at applyMap

### ISSUE THREAD

**Issue by jensCocquyt** [jspm/jspm-cli#2313]
When running jspm update we get the following error:

> err  TypeError: toMap.startsWith is not a function at applyMap (%appdata%\Roaming\npm\node_modules\jspm\lib\build.js:251:15)
         at %appdata%\Roaming\npm\node_modules\jspm\lib\build.js:527:30
         at String.replace (native)
         at RegExp.<anonymous> (%appdata%\Roaming\npm\node_modules\jspm\node_modules\core-js\modules\$.fix-re-wks.js:20:48)
         at String.replace (%appdata%\Roaming\npm\node_modules\jspm\node_modules\core-js\modules\es6.regexp.replace.js:9:12)
         at %appdata%\Roaming\npm\node_modules\jspm\lib\build.js:524:31
         at tryCatch (%appdata%\Roaming\npm\node_modules\jspm\node_modules\rsvp\dist\rsvp.js:539:12)
         at invokeCallback (%appdata%\Roaming\npm\node_modules\jspm\node_modules\rsvp\dist\rsvp.js:554:13)
         at publish (%appdata%\Roaming\npm\node_modules\jspm\node_modules\rsvp\dist\rsvp.js:522:7)
         at flush (%appdata%\Roaming\npm\node_modules\jspm\node_modules\rsvp\dist\rsvp.js:2414:5)
         at doNTCallback0 (node.js:428:9)
         at process._tickCallback (node.js:357:13)
warn Installation changes not saved.

Jspm: 0.16.19

Any idea?

**Comment by jensCocquyt** [comment]
Issue closed. Magically solved and can't reproduce.

**Comment by ecdavis15** [comment]
Has anyone else come across this issue? I'm working with jspm version 0.15.7 and am seeing the issue.

**Comment by m0ru** [comment]
using jspm 0.16.19 here and i get:
```
err  TypeError: toMap.startsWith is not a function
         at applyMap (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\jspm\lib\build.js:251:15)
         at C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\jspm\lib\build.js:527:30
         at String.replace (<anonymous>)
         at C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\jspm\lib\build.js:524:31
         at tryCatch (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\rsvp\dist\rsvp.js:525:12)
         at invokeCallback (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\rsvp\dist\rsvp.js:538:13)
         at publish (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\rsvp\dist\rsvp.js:508:7)
         at flush (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\rsvp\dist\rsvp.js:2415:5)
         at process._tickCallback (internal/process/next_tick.js:150:11)
```
